note=[]
username = input('Введите имя пользователя: ')
content = input('Введите описание заметки: ')
status = input('Введите статус заметки: ')
created_date = input('Введите дату создания заметки в формате "день-месяц-год": ')
date_of_change = input('Введите дату именения заметки в формате "день-месяц-год": ')
headlines = []
a = input('Введите заголовок: ')
b = input('Введите заголовок: ')
c = input('Введите заголовок: ')
headlines.append(a)
headlines.append(b)
headlines.append(c)
note.append(username)
note.append(content)
note.append(status)
note.append(created_date)
note.append(date_of_change)
note.append(headlines)
print(note)
