note=[]
username = input('Введите имя пользователя: ')
content = input('Введите описание заметки: ')
status = input('Введите статус заметки: ')
created_date = input('Введите дату создания заметки в формате "день-месяц-год" "xx-xx-xxxx": ')
issue_date = input('Введите дату истечения заметки в формате "день-месяц-год" "xx-xx-xxxx": ')
headlines = []
a = input('Заголовок1: ')
b = input('Заголовок2: ')
headlines.append(a)
headlines.append(b)
note.append(username)
note.append(content)
note.append(status)
note.append(created_date)
note.append(date_of_change)
note.append(headlines)
print(note)
